#!/bin/bash
#
# repository-installer This will install initial software for a fedora commons 3.8.1 server
# 
# chkconfig: 2345 9 20
# description: do things on firstboot to setup the server

# Fail if one of the functions fail.
set -e
randpw ()
{
    date +%s | sha256sum | base64 | head -c 7 ; echo
}

start()
{
        cd /opt;
        if [ -d /opt/fedora-repository ]; then
            echo "Fedora Repository is already installed on this machine!"
            echo "Please rename or remove the /opt/fedora-repository first and rerun this installer."
            echo "(service repository-installer start)"
            echo ""
            echo "Deactivating this installer service from starting at boot"
            echo "(chkconfig off repository-installer)"
            echo ""
            chkconfig repository-intstaller off
            exit 1;
        else
        yum -y install git gettext sendmail
        git clone https://github.com/dhinitiative/fedora-repository.git;
        chkconfig repository-installer off;
        fi
    return 0;
}

configure-email()
{
    sed -i "s|youremail@domain.com|<REPLACE WITH YOUR EMAIL>|g" /opt/fedora-repository/installer.sh
    return 0;
}

create-fuser-password()
{
    FUSER_PASS=`randpw`
    sed -i "s|fedora2014|$FUSER_PASS|g" /opt/fedora-repository/installer.sh
        return 0;
}
create-fedoradbpass()
{
    FDB_PASS=`randpw`
        sed -i "s|fedoradbpass|$FDB_PASS|g" /opt/fedora-repository/installer.sh
        return 0;
}
create-fedoraadminpass()
{
        FADMIN_PASS=`randpw`
        sed -i "s|fedoraadminpass|$FADMIN_PASS|g" /opt/fedora-repository/installer.sh
        return 0;
}
create-fgsadminpass()
{
       FGSADMIN_PASS=`randpw`
       sed -i "s|fgsadminpass|$FGSADMIN_PASS|g" /opt/fedora-repository/installer.sh
       return 0;
}
create-mysqlroot()
{
       MYSQL_PASS=`randpw`
       sed -i "s|mysqlroot|$MYSQL_PASS|g" /opt/fedora-repository/installer.sh
       return 0;
}
do-install()
{
    #
    # Note: it is assumed that we are installing this into /opt/fedora-repository
    #      update the path if you change this installation prefix
    #
    chmod 755 /opt/fedora-repository/installer.sh
    cd /opt/fedora-repository
    ./installer.sh >/opt/fedora-repository/installation.log 2>&1 &
    echo "Running the installation script...."
    echo "To watch the installation process run the command:"
    echo "tail -f /opt/fedora-repository/installation.log"
    echo "Please be patient as this installation process can take up to an hour"
    echo ""
}

case "$1" in
  start)
        echo $"Installing fedora-repository software in /opt.... "
    start
    configure-email
    create-fuser-password
    create-fedoradbpass
    create-fedoraadminpass
    create-fgsadminpass
    create-mysqlroot
    do-install
  ;;
  stop|status|restart|reload|force-reload)
   # do nothing
 ;;
esac
